### ISSUE TITLE
Android版本中设置界面的UI适配问题

### ISSUE THREAD

**Issue by SZH0728** [MinRi2/MinerTools#12]
与原先的设置界面相比，新的界面确实更加美观。
但是，在Android的设置界面中，会因为屏幕宽度不足而导致文字被遮挡。

Mindustry: Build 146
MinerTools: V2.0
![Screenshot_2024-02-11_edit_io anuke mindustry](https://github.com/MinRi2/MinerTools/assets/102466350/98fe2fc8-592c-4631-b665-40bfe5d46cc3)

**Comment by MinRi2** [comment]
确实是件头疼的事

**Comment by MinRi2** [comment]
已修复 新版本不会立即发布 可以前往[Actions](https://github.com/MinRi2/MinerTools/actions/runs/7860788355)下载最新构建版本
![64c3159377c8d5cd7289098a7f28b1de](https://github.com/MinRi2/MinerTools/assets/85016284/fa052efc-643d-4f71-a0f0-aa18c53fe1ac)
