### ISSUE TITLE
移动端UI超出屏幕显示

### ISSUE THREAD

**Issue by fengyulong01** [MinRi2/MinerTools#14]
移动端1080P分辨率设备下，游戏使用默认UI缩放值会导致MODUI部分显示内容超出物理屏幕边界无法显示出来。
1、建议增加MOD内UI缩放功能;
2、建议更改默认MOD缩放值。
如图：![Screenshot_2024-03-15-21-38-56-346_io.anuke.mindustry.jpg](https://github.com/MinRi2/MinerTools/assets/78330155/bcc09520-f00b-4b36-8e0e-f1ab8cff6a06)

**Comment by MinRi2** [comment]
见#12
