### ISSUE TITLE
ui bug

### ISSUE THREAD

**Issue by qaq1000w** [MinRi2/MinerTools#16]
![Screenshot_2024-07-04-13-42-27-850_io anuke mindustry](https://github.com/MinRi2/MinerTools/assets/80654352/b0c74639-e6c1-432e-8849-aaac3e2eca24)
缩小窗口和展开窗口时，按钮会重复

**Comment by MinRi2** [comment]
问一下 您的版本是

**Comment by MinRi2** [comment]
v2.1.0已修
