### ISSUE TITLE
Crash after joining the server

### ISSUE THREAD

**Issue by superdinmc** [MinRi2/MinerTools#6]
![image](https://user-images.githubusercontent.com/42496449/213863971-ba841a77-44ac-4522-aecb-ba71af49e6c2.png)
It warp my cam to middle of the map the shake a bit and then 2 seconds later, it crash with error above.

**Comment by 5UP3R-D1N** [comment]
In single player it tp my cam here and i cant stop
![image](https://user-images.githubusercontent.com/42496449/213864043-4ca5a502-d617-4f7c-9e81-14603b505bca.png)

**Comment by MinRi2** [comment]
I will disable the cutscene on default. :)
