### ISSUE TITLE
Mod đè lên các phần chọn công trình xây dựng

### ISSUE THREAD

**Issue by Thai3101** [MinRi2/MinerTools#7]
Mod bị chuyển xuống phần dưới làm tôi không thể xây dựng các công trình khác , do nó đã bị mod đè lên  

The mod was moved to the lower part, making it impossible for me to build other buildings, because it was overwritten by the mod

![Screenshot_2023-05-07-07-39-58-65](https://user-images.githubusercontent.com/112742363/236652056-e8d32422-3d33-486e-8fa4-aa8503366ba9.jpg)

**Comment by MinRi2** [comment]
You can try to change your ui scale in the setting. In the next  version i will turn it into a FloatTable. :)
